<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Cache\Cache;
use Cake\Event\EventInterface;

/**
 * Admin Controller
 *
 * @method \App\Model\Entity\Admin[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AdminController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        if(!$this->Authentication->getIdentity()->get('uti_is_admin')){
            $this->Flash->error(__('Vous n\'avez pas l\'autorisation de consulter cette page.'));
            $this->redirect('/');
        }
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function index()
    {

    }
}
