<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Cache\Cache;
use Cake\Event\EventInterface;

/**
 * Admin Controller
 *
 * @method \App\Model\Entity\Admin[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AdminController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        if (!$this->Authentication->getIdentity()->get('uti_is_admin')) {
            $this->Flash->error(__('Vous n\'avez pas l\'autorisation de consulter cette page.'));
            $this->redirect('/');
        }
    }

    public function upload()
    {
        if (!$this->Authentication->getIdentity()->get('uti_is_admin')) {
            $this->Flash->error(__('Vous n\'avez pas l\'autorisation de consulter cette page.'));
            return;
        }

        if ($this->request->is('post')) {
            //on vérifie que les dossiers existent bien
            $targetPath = WWW_ROOT . 'img' . DS . 'upload';
            $date = $this->request->getData('date');
            $dossier = $this->request->getData('dir');
            foreach (explode('-', $date) as $dir) {
                $targetPath .= DS . $dir;
                if (!is_dir($targetPath)) {
                    mkdir($targetPath);
                }
            }
            $targetPath .= DS . str_replace(' ', '_', $dossier);
            if (!is_dir($targetPath)) {
                mkdir($targetPath);
            }

            $image = $this->request->getData('photo');
            $name = $image->getClientFileName();
            $type = $image->getClientMediaType();
            $targetPath .= DS . $name;
            if ($type == 'image/jpeg' || $type == 'image/jpg' || $type == 'image/png') {
                if (!empty($name)) {
                    if ($image->getSize() > 0 && $image->getError() == 0) {
                        if (!file_exists($targetPath)) {
                            $this->loadModel('ParPhoto');
                            $this->ParPhoto->insertPhoto($name, explode('-', $date)[0], explode('-', $date)[1], explode('-', $date)[2], $dossier, $this->Authentication->getIdentity()->get('uti_lien'));
                            $image->moveTo($targetPath);
                        }
                    }
                }
            }
            die;
        }
        $this->redirect('/admin');
    }

    public function nbAAssigner()
    {
        if (!$this->Authentication->getIdentity()->get('uti_is_admin')) {
            $this->Flash->error(__('Vous n\'avez pas l\'autorisation de consulter cette page.'));
            return;
        }

        if ($this->request->is('post')) {
            $this->loadModel("ParAssigner");
            $nb = $this->ParAssigner->getNbAAssigner();
            return $this->response->withStringBody($nb . "");
        }
        $this->redirect('/admin');
    }

}
