<?php

namespace App\Controller;

class DownloadController extends AppController
{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->set(['item' => "photos"]);
    }

    public function photo($pho_lien) {

        $this->loadModel('ParPhoto');
        $infos = $this->ParPhoto->getPhotoInfos($pho_lien);

        if(!empty($infos)){
            header('Content-disposition: attachment; filename="' . $infos['pho_nom'] . '"');
            header('Content-Type: image');
            readfile('img/upload/'. $infos['pho_annee'] .'/' . ($infos['pho_mois'] < 10 ? '0' . $infos['pho_mois'] : $infos['pho_mois']) . '/' . ($infos['pho_jour'] < 10 ? '0' . $infos['pho_jour'] : $infos['pho_jour']) . '/' . $infos['pho_dossier'] . '/' . $infos['pho_nom']);
            die();
        }
        $this->Flash->error('Impossible de télécharger l\'image demandée.');
        return $this->redirect('/');
    }

}
